@startuml ユースケース図
left to right direction
' actor 利用者
'  rectangle ホテル宿泊予約{
'    ' usecase ログイン
'     usecase (<u>宿泊予約</u>\n拡張点\nキャンペーン期間) as input
'     usecase キャンペーン価格
'  }
'  利用者 --> input
' '  ログイン .> input : << include >>
'  キャンペーン価格 <. input : << extend >>

 left to right direction
actor 利用者
 rectangle ホテル宿泊予約{
    usecase (<u>宿泊予約</u>\n拡張点\nキャンペーン期間) as input
    usecase キャンペーン価格
    usecase ログイン

 }
 利用者 --> input
 キャンペーン価格 <. input : << extend >>
 ログイン .> input: << include >>
 

@enduml