@startuml  
object "<u>301号室:Aさん </u>" as 301 {
宿泊費 = 11,000
タイプ:シングル
チェックイン日 = 5月3日
チェックアウト日 = 5月5日
}
object "<u>302号室:空室 </u>" as 302 {
宿泊費 = 11,000
タイプ:シングル
チェックイン日 = none
チェックアウト日 = none
}
object "<u>303号室:Bさん </u>" as 303 {
宿泊費 = 11,000
タイプ:シングル
チェックイン日 = 5月3日
チェックアウト日 = 5月5日
}
object "<u>キャンペーン期間:4月29日から5月6日 </u>" as campaign {
宿泊費 = 9,000
}

301 "1" -left- "1"  campaign
302 "1" -up- "1"  campaign
303 "1" -- "1"  campaign

@enduml