@startuml  

object "<u>テレビ:商品 </u>" as merchandise1 {
商品名
型式
}

object "<u>冷蔵庫:商品 </u>" as merchandise2 {
商品名
型式
}


' object "<u>:注文 </u>" as  {
' 注文日
' 数量
' }

object "<u>高田利恵:顧客 </u>" as customer {
注文日
住所
}

object "<u>高橋洋平:重要顧客 </u>" as importantcustomer {
注文日
}

merchandise1 -ri- importantcustomer
merchandise2 -up- importantcustomer
merchandise2 -- customer
@enduml