@startuml  
left to right direction
skinparam ClassAttributeIconSize 0

class 医師{}
class 患者{}
class 患者の診察記録{}
class 医局{}

患者 "*" -- "1" 医師
医局 "1" -- "*" 医師

医師 --> 患者:診察 >
患者 <.. 患者の診察記録 
医師"担当医"-- 患者

hide 医師 circle
hide 患者 circle
hide 患者の診察記録 circle
hide 医局 circle

@enduml